# Generated by Django 5.0.1 on 2025-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('voice', 'Voice Input'), ('image', 'Image Input'), ('text', 'Text Input')], max_length=10)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='ingestion/')),
                ('input_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('gemini_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
