# Generated by Django 5.0.1 on 2025-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ingestion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
