# Generated by Django 5.0.1 on 2025-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('text', 'Text Search'), ('voice', 'Voice Search'), ('image', 'Image Search')], max_length=10)),
                ('query_text', models.TextField()),
                ('original_query', models.TextField(blank=True, null=True)),
                ('district_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('category_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('max_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('search_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('search_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('query_embedding', models.JSONField(blank=True, default=list)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.PositiveIntegerField()),
                ('similarity_score', models.FloatField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_results',
                'ordering': ['rank_position'],
            },
        ),
    ]
