# Generated by Django 5.0.1 on 2025-11-16 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_product_created',
            old_name='products_created_a77fb9_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_product_district_active',
            old_name='products_distric_0e7d24_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_product_category_active',
            old_name='products_categor_9e60b3_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['district'], name='idx_product_district'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_product_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='idx_product_seller'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['district', 'category', 'is_active'], name='idx_product_search'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'is_active'], name='idx_product_seller_active'),
        ),
    ]
